# Generated by Django 3.2.3 on 2021-11-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211105_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='verified',
        ),
    ]
