# Generated by Django 3.2.3 on 2021-11-08 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.session'),
        ),
    ]
