# Generated by Django 3.2.3 on 2021-11-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.session'),
        ),
    ]
