# Generated by Django 3.2.3 on 2021-11-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_useraccount_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='auth_token',
        ),
    ]
